language: node_js

node_js:
  - "0.10"
# TODO: - "0.11"

before_install:
  - ruby --version
  - gem update --system
  - gem install bundler
  - gem --version
  - bundle --version
  - bundle config build.nokogiri --use-system-libraries

install:
  - travis_retry bundle install --jobs=3
  - travis_retry bundle exec npm install -g gulp
  - travis_retry bundle exec npm install

script:
  - bundle exec gulp sinon.js
  - bundle exec gulp test
  - bundle exec gulp build

