language: node_js

node_js:
  - "0.10"
# TODO: - "0.11"

before_install:
  - gem update --system
  - bundle config build.nokogiri --use-system-libraries

install:
  - travis_retry gem install juicer
  - travis_retry gem install sass
  - travis_retry npm install -g gulp
  - travis_retry npm install
  - travis_retry bundle install --jobs=3

script:
  - gulp sinon.js
  - gulp test
  - gulp build

