language: node_js

node_js:
  - "0.10"

sudo: false

install:
  - travis_retry bundle install -j4 --path vendor/bundle
  - travis_retry npm install -g gulp
  - travis_retry npm install -g bower
  - npm prune
  - bower prune
  - travis_retry npm install

script:
  - gulp test
  - gulp build

deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: "jSQwjYD/vSV1mEElK50xgND+R/jh520z5OY78DcNm/995B/tWdDrQRLweSwvLpGiZXQulQs+6pYNY9j807OEIwcNIuqJO7iDtJm2SEXmgi4YnfSkDhijlnil3/9FIh1R4jCodAqK/gQqtXwQCipvPb4yPMPPMFjoqFE4Q4CJGVc="
  app:
    master: sspm-mock

cache:
  directories:
    - vendor/bundle
    - bower_components
    - node_modules
