language: node_js

node_js:
  - "0.10"
# TODO: - "0.11"

sudo: false

before_install:
  - rvm use 2.1 --install --binary --fuzzy
  - ruby --version
  - gem update --system
  - gem install bundler
  - gem --version
  - bundle --version
  - bundle config build.nokogiri --use-system-libraries

install:
  - travis_retry bundle install --jobs=3
  - travis_retry bundle exec npm install -g gulp
  - travis_retry bundle exec npm install

script:
  - bundle exec gulp sinon.js
  - bundle exec gulp test
  - bundle exec gulp build

deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: "jSQwjYD/vSV1mEElK50xgND+R/jh520z5OY78DcNm/995B/tWdDrQRLweSwvLpGiZXQulQs+6pYNY9j807OEIwcNIuqJO7iDtJm2SEXmgi4YnfSkDhijlnil3/9FIh1R4jCodAqK/gQqtXwQCipvPb4yPMPPMFjoqFE4Q4CJGVc="
  app:
    master: sspm-mock

